///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Market_Preferences
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Check_For_Brand recording.
    /// </summary>
    [TestModule("3c994668-1120-4540-8b00-be41e39ce046", ModuleType.Recording, 1)]
    public partial class Check_For_Brand : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Market_PreferencesRepository repository.
        /// </summary>
        public static Market_PreferencesRepository repo = Market_PreferencesRepository.Instance;

        static Check_For_Brand instance = new Check_For_Brand();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Check_For_Brand()
        {
            txtBrandname = "";
            ReturnBrandname = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Check_For_Brand Instance
        {
            get { return instance; }
        }

#region Variables

        string _txtBrandname;

        /// <summary>
        /// Gets or sets the value of variable txtBrandname.
        /// </summary>
        [TestVariable("743af0cd-9558-49f9-b63f-933678d5c3b3")]
        public string txtBrandname
        {
            get { return _txtBrandname; }
            set { _txtBrandname = value; }
        }

        string _ReturnBrandname;

        /// <summary>
        /// Gets or sets the value of variable ReturnBrandname.
        /// </summary>
        [TestVariable("08f2bf96-188f-46bd-babb-aa3bc312623c")]
        public string ReturnBrandname
        {
            get { return _ReturnBrandname; }
            set { _ReturnBrandname = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            ReturnBrandname = CheckForBrand_UserCodeCollection.BrandCheck(txtBrandname);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
