///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Market_Preferences
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Market_PreferencesRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ef6d43ec-7390-41d3-9583-9a4abc6cdeba")]
    public partial class Market_PreferencesRepository : RepoGenBaseFolder
    {
        static Market_PreferencesRepository instance = new Market_PreferencesRepository();
        Market_PreferencesRepositoryFolders.WindowAppFolder _window;
        Market_PreferencesRepositoryFolders.SmartFitAppFolder _smartfit;
        Market_PreferencesRepositoryFolders.FSWModule_RepoAppFolder _fswmodule_repo;
        Market_PreferencesRepositoryFolders.PopupAppFolder _popup;
        Market_PreferencesRepositoryFolders.SmartFit15InstallShieldWizardAppFolder _smartfit15installshieldwizard;
        Market_PreferencesRepositoryFolders.List1000AppFolder _list1000;
        Market_PreferencesRepositoryFolders.MyReSoundAppFolder _myresound;
        Market_PreferencesRepositoryFolders.SmartFit1AppFolder _smartfit1;

        /// <summary>
        /// Gets the singleton class instance representing the Market_PreferencesRepository element repository.
        /// </summary>
        [RepositoryFolder("ef6d43ec-7390-41d3-9583-9a4abc6cdeba")]
        public static Market_PreferencesRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Market_PreferencesRepository() 
            : base("Market_PreferencesRepository", "/", null, 0, false, "ef6d43ec-7390-41d3-9583-9a4abc6cdeba", ".\\RepositoryImages\\Market_PreferencesRepositoryef6d43ec.rximgres")
        {
            _window = new Market_PreferencesRepositoryFolders.WindowAppFolder(this);
            _smartfit = new Market_PreferencesRepositoryFolders.SmartFitAppFolder(this);
            _fswmodule_repo = new Market_PreferencesRepositoryFolders.FSWModule_RepoAppFolder(this);
            _popup = new Market_PreferencesRepositoryFolders.PopupAppFolder(this);
            _smartfit15installshieldwizard = new Market_PreferencesRepositoryFolders.SmartFit15InstallShieldWizardAppFolder(this);
            _list1000 = new Market_PreferencesRepositoryFolders.List1000AppFolder(this);
            _myresound = new Market_PreferencesRepositoryFolders.MyReSoundAppFolder(this);
            _smartfit1 = new Market_PreferencesRepositoryFolders.SmartFit1AppFolder(this);
        }

#region Variables

        string _TxtMkt = "";

        /// <summary>
        /// Gets or sets the value of variable TxtMkt.
        /// </summary>
        [TestVariable("ffe224a2-607e-44cd-80df-a0f4401ec54c")]
        public string TxtMkt
        {
            get { return _TxtMkt; }
            set { _TxtMkt = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ef6d43ec-7390-41d3-9583-9a4abc6cdeba")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Window folder.
        /// </summary>
        [RepositoryFolder("decbf21a-2bcf-4d58-b370-dad3829dc2f3")]
        public virtual Market_PreferencesRepositoryFolders.WindowAppFolder Window
        {
            get { return _window; }
        }

        /// <summary>
        /// The SmartFit folder.
        /// </summary>
        [RepositoryFolder("294f7592-db9b-4ca5-8893-1fac816191d2")]
        public virtual Market_PreferencesRepositoryFolders.SmartFitAppFolder SmartFit
        {
            get { return _smartfit; }
        }

        /// <summary>
        /// The FSWModule_Repo folder.
        /// </summary>
        [RepositoryFolder("620b9651-d9f6-4556-bca4-7f2bf50b57e3")]
        public virtual Market_PreferencesRepositoryFolders.FSWModule_RepoAppFolder FSWModule_Repo
        {
            get { return _fswmodule_repo; }
        }

        /// <summary>
        /// The Popup folder.
        /// </summary>
        [RepositoryFolder("c1a0e544-e3de-4322-8b9f-b04d4735c7d2")]
        public virtual Market_PreferencesRepositoryFolders.PopupAppFolder Popup
        {
            get { return _popup; }
        }

        /// <summary>
        /// The SmartFit15InstallShieldWizard folder.
        /// </summary>
        [RepositoryFolder("b930523e-1185-4175-bb43-7b0ce14587db")]
        public virtual Market_PreferencesRepositoryFolders.SmartFit15InstallShieldWizardAppFolder SmartFit15InstallShieldWizard
        {
            get { return _smartfit15installshieldwizard; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("ba1cf351-1a8d-4f26-bda5-f1a1df6903e4")]
        public virtual Market_PreferencesRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The MyReSound folder.
        /// </summary>
        [RepositoryFolder("eb4ad3f2-ce76-4e5e-ab3b-9571cc6fe117")]
        public virtual Market_PreferencesRepositoryFolders.MyReSoundAppFolder MyReSound
        {
            get { return _myresound; }
        }

        /// <summary>
        /// The SmartFit1 folder.
        /// </summary>
        [RepositoryFolder("de40901e-2d4c-4fa3-97c8-dc4331311fd3")]
        public virtual Market_PreferencesRepositoryFolders.SmartFit1AppFolder SmartFit1
        {
            get { return _smartfit1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Market_PreferencesRepositoryFolders
    {
        /// <summary>
        /// The WindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("decbf21a-2bcf-4d58-b370-dad3829dc2f3")]
        public partial class WindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _partextendedscrollviewerInfo;
            RepoItemInfo _partobjectnametextblockInfo;
            RepoItemInfo _remotefinetuningInfo;
            RepoItemInfo _defaultenvironmentalprogramsInfo;
            RepoItemInfo _remotehearingaidupdateInfo;
            RepoItemInfo _comboboxInfo;
            RepoItemInfo _partsegmentedtogglebuttonInfo;
            RepoItemInfo _combobox1Info;
            RepoItemInfo _partobjectnametextblock1Info;
            RepoItemInfo _editInfo;
            RepoItemInfo _partusepincodecheckboxInfo;
            RepoItemInfo _partobjectnametextblock2Info;
            RepoItemInfo _partsegmentedtogglebutton1Info;
            RepoItemInfo _copy_of_partsegmentedtogglebutton1Info;
            RepoItemInfo _groupboxInfo;
            RepoItemInfo _copy_of_partextendedscrollviewerInfo;
            RepoItemInfo _copy_of_comboboxInfo;
            RepoItemInfo _partupdatescheckonschedulecheckInfo;
            RepoItemInfo _partcontenthostInfo;
            RepoItemInfo _save_buttonInfo;
            RepoItemInfo _copy_of_save_buttonInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _exit_without_savingInfo;
            RepoItemInfo _combobox2Info;
            RepoItemInfo _thumbInfo;
            RepoItemInfo _partpositivebuttonInfo;
            RepoItemInfo _menuautomationidsinstrumentactionInfo;
            RepoItemInfo _menuautomationidsviewactionInfo;
            RepoItemInfo _back_buttonInfo;
            RepoItemInfo _listboxInfo;
            RepoItemInfo _bimodal_radiobuttonInfo;
            RepoItemInfo _dialogautomationidspositiveactionInfo;
            RepoItemInfo _copy_of_combobox2Info;
            RepoItemInfo _copy_of_partcontenthostInfo;
            RepoItemInfo _modelodoaparelhoInfo;

            /// <summary>
            /// Creates a new Window  folder.
            /// </summary>
            public WindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Window", "/form[@classname='Window' and @orientation='None' and @processname='SmartFit' or @processname='SolusMax']", parentFolder, 30000, null, false, "decbf21a-2bcf-4d58-b370-dad3829dc2f3", "")
            {
                _partextendedscrollviewerInfo = new RepoItemInfo(this, "PARTExtendedScrollViewer", "container[@automationid='PART_ExtendedScrollViewer']", 30000, null, "5160f56a-7511-4211-b3f6-2765c2a04af6");
                _partobjectnametextblockInfo = new RepoItemInfo(this, "PARTObjectNameTextBlock", "?/?/container[@name>'Default Environmental Pro']/text[@name='1.']", 30000, null, "ecd144d0-c870-4dfc-9dcc-386eebc5a12c");
                _remotefinetuningInfo = new RepoItemInfo(this, "RemoteFineTuning", "?/?/container[@name='Remote Fine-tuning']", 30000, null, "105561f5-3621-4471-8530-27156eb4ca90");
                _defaultenvironmentalprogramsInfo = new RepoItemInfo(this, "DefaultEnvironmentalPrograms", "?/?/container[@name>'Default Environmental Pro']", 30000, null, "6901ad86-7c8e-4351-b677-c1f9653fa2eb");
                _remotehearingaidupdateInfo = new RepoItemInfo(this, "RemoteHearingAidUpdate", "?/?/container[@name='Remote Hearing Aid Update']", 30000, null, "d93e4347-54b6-4ff3-a3b2-81944e977337");
                _comboboxInfo = new RepoItemInfo(this, "ComboBox", "container/combobox[1]", 30000, null, "8a59da9d-0116-4f68-aa29-580bfff33736");
                _partsegmentedtogglebuttonInfo = new RepoItemInfo(this, "PARTSegmentedToggleButton", "container/button[1]", 30000, null, "b83f0eb7-bbe4-4708-8b51-376e1d12a628");
                _combobox1Info = new RepoItemInfo(this, "ComboBox1", "container/container[2]/button[1]", 30000, null, "6ac29d5f-d5a3-41c0-b50c-337b72523bef");
                _partobjectnametextblock1Info = new RepoItemInfo(this, "PARTObjectNameTextBlock1", "?/?/container[@name='Remote Hearing Aid Update']/button[@name='Yes']/text[@name='No']", 30000, null, "49e32bb4-91c4-4534-a5e6-87aa9d2f4996");
                _editInfo = new RepoItemInfo(this, "Edit", "?/?/menuitem[@name='Edit']", 30000, null, "1de7ad0d-68c3-41e5-a6b3-31570666540b");
                _partusepincodecheckboxInfo = new RepoItemInfo(this, "PARTUsePinCodeCheckBox", "container/checkbox[@automationid='PART_UsePinCodeCheckBox']", 30000, null, "428b7797-ac7e-4641-91bc-b7218411fba0");
                _partobjectnametextblock2Info = new RepoItemInfo(this, "PARTObjectNameTextBlock2", "?/?/button[@automationid='PART_SegmentedToggleButton']/text[@name='No']", 30000, null, "fbe2ddb8-61e4-46a4-ba24-994e489a6216");
                _partsegmentedtogglebutton1Info = new RepoItemInfo(this, "PARTSegmentedToggleButton1", "container/button[@automationid='PART_SegmentedToggleButton']", 30000, null, "3b75eac6-bec2-4054-9f1a-c2e41191bd9a");
                _copy_of_partsegmentedtogglebutton1Info = new RepoItemInfo(this, "Copy_of_PARTSegmentedToggleButton1", "container/button[1]", 30000, null, "71ac83ad-7cf7-4390-be0f-1106093ad93b");
                _groupboxInfo = new RepoItemInfo(this, "GroupBox", "?/?/container[@classname='GroupBox']", 30000, null, "07bb4991-e4d9-41ff-ae93-cfe3207db44b");
                _copy_of_partextendedscrollviewerInfo = new RepoItemInfo(this, "Copy_of_PARTExtendedScrollViewer", "container[@automationid='PART_ExtendedScrollViewer']/container", 30000, null, "12d1d401-b97f-49c3-9199-cff18a9bbbfa");
                _copy_of_comboboxInfo = new RepoItemInfo(this, "Copy_of_ComboBox", "container/container/combobox[1]", 30000, null, "4ac65433-920a-4eff-9536-7b3011e86f1a");
                _partupdatescheckonschedulecheckInfo = new RepoItemInfo(this, "PARTUpdatesCheckOnScheduleCheck", "container/container/checkbox[3]", 30000, null, "d4089d2f-2954-4eaa-b766-325473d7ecea");
                _partcontenthostInfo = new RepoItemInfo(this, "PARTContentHost", "text/container[@automationid='PART_ContentHost']", 30000, null, "4c61107c-c64a-4d05-894c-fa9f30eee805");
                _save_buttonInfo = new RepoItemInfo(this, "Save_Button", "button[4]", 30000, null, "f64a5e52-9acc-4d2f-b8be-8570ff447d9d");
                _copy_of_save_buttonInfo = new RepoItemInfo(this, "Copy_of_Save_Button", "button[5]", 30000, null, "33abaeda-ebaa-4d3a-ba7e-88401870f990");
                _closeInfo = new RepoItemInfo(this, "Close", "button[@name='Close']", 30000, null, "2ffac5df-a3c6-4978-9b1a-76ea0e207dd1");
                _exit_without_savingInfo = new RepoItemInfo(this, "Exit_Without_saving", "button[2]", 30000, null, "4070c00e-f274-4313-ba46-8bb7579628f0");
                _combobox2Info = new RepoItemInfo(this, "ComboBox2", "container/combobox[2]", 30000, null, "edbd935c-5039-4e08-a6cd-7370ce00e9c9");
                _thumbInfo = new RepoItemInfo(this, "Thumb", "?/?/scrollbar[@automationid='VerticalScrollBar']/indicator[@classname='Thumb']", 30000, null, "d4254311-ea66-4c7e-ba29-a7707261454e");
                _partpositivebuttonInfo = new RepoItemInfo(this, "PARTPositiveButton", "button[@automationid='PART_PositiveButton']", 30000, null, "2d47b80d-5978-42ac-8d5b-be30c80a8977");
                _menuautomationidsinstrumentactionInfo = new RepoItemInfo(this, "MenuAutomationIdsInstrumentAction", "?/?/menuitem[@automationid='MenuAutomationIds.InstrumentAction']", 30000, null, "e19bb8af-e919-40ef-b637-0283ccb77672");
                _menuautomationidsviewactionInfo = new RepoItemInfo(this, "MenuAutomationIdsViewAction", "?/?/menuitem[@automationid='MenuAutomationIds.ViewAction']", 30000, null, "1fec0964-ddd2-425d-a0b4-db883956abf4");
                _back_buttonInfo = new RepoItemInfo(this, "Back_Button", "button[2]", 60000, null, "359ff0df-5289-444a-82f1-faa5b98448bc");
                _listboxInfo = new RepoItemInfo(this, "ListBox", "container[@automationid='PART_ExtendedScrollViewer']/list[3]", 30000, null, "27b251af-b1d9-4334-9265-84fc0fdb69c5");
                _bimodal_radiobuttonInfo = new RepoItemInfo(this, "BiModal_RadioButton", "container/button[8]", 30000, null, "a4647678-c87a-44ac-bb94-1dd50d933487");
                _dialogautomationidspositiveactionInfo = new RepoItemInfo(this, "DialogAutomationIdsPositiveAction", "button[@automationid='DialogAutomationIds.PositiveAction']", 30000, null, "6c13bf68-24ff-4dc9-b6cd-bced76f9ce9a");
                _copy_of_combobox2Info = new RepoItemInfo(this, "Copy_of_ComboBox2", "container/combobox[7]", 30000, null, "d7b1b1bc-2c4c-43a6-b2eb-f71f16b0ba3a");
                _copy_of_partcontenthostInfo = new RepoItemInfo(this, "Copy_of_PARTContentHost", "text", 30000, null, "ad3eb913-f5a7-4901-8087-abe48e16e01e");
                _modelodoaparelhoInfo = new RepoItemInfo(this, "ModeloDoAparelho", "?/?/text[@name='Modelo do Aparelho']", 30000, null, "ffbd9d41-25e8-4fee-a119-932c8fb3a27c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("decbf21a-2bcf-4d58-b370-dad3829dc2f3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("decbf21a-2bcf-4d58-b370-dad3829dc2f3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PARTExtendedScrollViewer item.
            /// </summary>
            [RepositoryItem("5160f56a-7511-4211-b3f6-2765c2a04af6")]
            public virtual Ranorex.Container PARTExtendedScrollViewer
            {
                get
                {
                    return _partextendedscrollviewerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PARTExtendedScrollViewer item info.
            /// </summary>
            [RepositoryItemInfo("5160f56a-7511-4211-b3f6-2765c2a04af6")]
            public virtual RepoItemInfo PARTExtendedScrollViewerInfo
            {
                get
                {
                    return _partextendedscrollviewerInfo;
                }
            }

            /// <summary>
            /// The PARTObjectNameTextBlock item.
            /// </summary>
            [RepositoryItem("ecd144d0-c870-4dfc-9dcc-386eebc5a12c")]
            public virtual Ranorex.Text PARTObjectNameTextBlock
            {
                get
                {
                    return _partobjectnametextblockInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PARTObjectNameTextBlock item info.
            /// </summary>
            [RepositoryItemInfo("ecd144d0-c870-4dfc-9dcc-386eebc5a12c")]
            public virtual RepoItemInfo PARTObjectNameTextBlockInfo
            {
                get
                {
                    return _partobjectnametextblockInfo;
                }
            }

            /// <summary>
            /// The RemoteFineTuning item.
            /// </summary>
            [RepositoryItem("105561f5-3621-4471-8530-27156eb4ca90")]
            public virtual Ranorex.Container RemoteFineTuning
            {
                get
                {
                    return _remotefinetuningInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The RemoteFineTuning item info.
            /// </summary>
            [RepositoryItemInfo("105561f5-3621-4471-8530-27156eb4ca90")]
            public virtual RepoItemInfo RemoteFineTuningInfo
            {
                get
                {
                    return _remotefinetuningInfo;
                }
            }

            /// <summary>
            /// The DefaultEnvironmentalPrograms item.
            /// </summary>
            [RepositoryItem("6901ad86-7c8e-4351-b677-c1f9653fa2eb")]
            public virtual Ranorex.Container DefaultEnvironmentalPrograms
            {
                get
                {
                    return _defaultenvironmentalprogramsInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The DefaultEnvironmentalPrograms item info.
            /// </summary>
            [RepositoryItemInfo("6901ad86-7c8e-4351-b677-c1f9653fa2eb")]
            public virtual RepoItemInfo DefaultEnvironmentalProgramsInfo
            {
                get
                {
                    return _defaultenvironmentalprogramsInfo;
                }
            }

            /// <summary>
            /// The RemoteHearingAidUpdate item.
            /// </summary>
            [RepositoryItem("d93e4347-54b6-4ff3-a3b2-81944e977337")]
            public virtual Ranorex.Container RemoteHearingAidUpdate
            {
                get
                {
                    return _remotehearingaidupdateInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The RemoteHearingAidUpdate item info.
            /// </summary>
            [RepositoryItemInfo("d93e4347-54b6-4ff3-a3b2-81944e977337")]
            public virtual RepoItemInfo RemoteHearingAidUpdateInfo
            {
                get
                {
                    return _remotehearingaidupdateInfo;
                }
            }

            /// <summary>
            /// The ComboBox item.
            /// </summary>
            [RepositoryItem("8a59da9d-0116-4f68-aa29-580bfff33736")]
            public virtual Ranorex.ComboBox ComboBox
            {
                get
                {
                    return _comboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox item info.
            /// </summary>
            [RepositoryItemInfo("8a59da9d-0116-4f68-aa29-580bfff33736")]
            public virtual RepoItemInfo ComboBoxInfo
            {
                get
                {
                    return _comboboxInfo;
                }
            }

            /// <summary>
            /// The PARTSegmentedToggleButton item.
            /// </summary>
            [RepositoryItem("b83f0eb7-bbe4-4708-8b51-376e1d12a628")]
            public virtual Ranorex.Button PARTSegmentedToggleButton
            {
                get
                {
                    return _partsegmentedtogglebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTSegmentedToggleButton item info.
            /// </summary>
            [RepositoryItemInfo("b83f0eb7-bbe4-4708-8b51-376e1d12a628")]
            public virtual RepoItemInfo PARTSegmentedToggleButtonInfo
            {
                get
                {
                    return _partsegmentedtogglebuttonInfo;
                }
            }

            /// <summary>
            /// The ComboBox1 item.
            /// </summary>
            [RepositoryItem("6ac29d5f-d5a3-41c0-b50c-337b72523bef")]
            public virtual Ranorex.Button ComboBox1
            {
                get
                {
                    return _combobox1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ComboBox1 item info.
            /// </summary>
            [RepositoryItemInfo("6ac29d5f-d5a3-41c0-b50c-337b72523bef")]
            public virtual RepoItemInfo ComboBox1Info
            {
                get
                {
                    return _combobox1Info;
                }
            }

            /// <summary>
            /// The PARTObjectNameTextBlock1 item.
            /// </summary>
            [RepositoryItem("49e32bb4-91c4-4534-a5e6-87aa9d2f4996")]
            public virtual Ranorex.Text PARTObjectNameTextBlock1
            {
                get
                {
                    return _partobjectnametextblock1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PARTObjectNameTextBlock1 item info.
            /// </summary>
            [RepositoryItemInfo("49e32bb4-91c4-4534-a5e6-87aa9d2f4996")]
            public virtual RepoItemInfo PARTObjectNameTextBlock1Info
            {
                get
                {
                    return _partobjectnametextblock1Info;
                }
            }

            /// <summary>
            /// The Edit item.
            /// </summary>
            [RepositoryItem("1de7ad0d-68c3-41e5-a6b3-31570666540b")]
            public virtual Ranorex.MenuItem Edit
            {
                get
                {
                    return _editInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Edit item info.
            /// </summary>
            [RepositoryItemInfo("1de7ad0d-68c3-41e5-a6b3-31570666540b")]
            public virtual RepoItemInfo EditInfo
            {
                get
                {
                    return _editInfo;
                }
            }

            /// <summary>
            /// The PARTUsePinCodeCheckBox item.
            /// </summary>
            [RepositoryItem("428b7797-ac7e-4641-91bc-b7218411fba0")]
            public virtual Ranorex.CheckBox PARTUsePinCodeCheckBox
            {
                get
                {
                    return _partusepincodecheckboxInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The PARTUsePinCodeCheckBox item info.
            /// </summary>
            [RepositoryItemInfo("428b7797-ac7e-4641-91bc-b7218411fba0")]
            public virtual RepoItemInfo PARTUsePinCodeCheckBoxInfo
            {
                get
                {
                    return _partusepincodecheckboxInfo;
                }
            }

            /// <summary>
            /// The PARTObjectNameTextBlock2 item.
            /// </summary>
            [RepositoryItem("fbe2ddb8-61e4-46a4-ba24-994e489a6216")]
            public virtual Ranorex.Text PARTObjectNameTextBlock2
            {
                get
                {
                    return _partobjectnametextblock2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PARTObjectNameTextBlock2 item info.
            /// </summary>
            [RepositoryItemInfo("fbe2ddb8-61e4-46a4-ba24-994e489a6216")]
            public virtual RepoItemInfo PARTObjectNameTextBlock2Info
            {
                get
                {
                    return _partobjectnametextblock2Info;
                }
            }

            /// <summary>
            /// The PARTSegmentedToggleButton1 item.
            /// </summary>
            [RepositoryItem("3b75eac6-bec2-4054-9f1a-c2e41191bd9a")]
            public virtual Ranorex.Button PARTSegmentedToggleButton1
            {
                get
                {
                    return _partsegmentedtogglebutton1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTSegmentedToggleButton1 item info.
            /// </summary>
            [RepositoryItemInfo("3b75eac6-bec2-4054-9f1a-c2e41191bd9a")]
            public virtual RepoItemInfo PARTSegmentedToggleButton1Info
            {
                get
                {
                    return _partsegmentedtogglebutton1Info;
                }
            }

            /// <summary>
            /// The Copy_of_PARTSegmentedToggleButton1 item.
            /// </summary>
            [RepositoryItem("71ac83ad-7cf7-4390-be0f-1106093ad93b")]
            public virtual Ranorex.Button Copy_of_PARTSegmentedToggleButton1
            {
                get
                {
                    return _copy_of_partsegmentedtogglebutton1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Copy_of_PARTSegmentedToggleButton1 item info.
            /// </summary>
            [RepositoryItemInfo("71ac83ad-7cf7-4390-be0f-1106093ad93b")]
            public virtual RepoItemInfo Copy_of_PARTSegmentedToggleButton1Info
            {
                get
                {
                    return _copy_of_partsegmentedtogglebutton1Info;
                }
            }

            /// <summary>
            /// The GroupBox item.
            /// </summary>
            [RepositoryItem("07bb4991-e4d9-41ff-ae93-cfe3207db44b")]
            public virtual Ranorex.Container GroupBox
            {
                get
                {
                    return _groupboxInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The GroupBox item info.
            /// </summary>
            [RepositoryItemInfo("07bb4991-e4d9-41ff-ae93-cfe3207db44b")]
            public virtual RepoItemInfo GroupBoxInfo
            {
                get
                {
                    return _groupboxInfo;
                }
            }

            /// <summary>
            /// The Copy_of_PARTExtendedScrollViewer item.
            /// </summary>
            [RepositoryItem("12d1d401-b97f-49c3-9199-cff18a9bbbfa")]
            public virtual Ranorex.Container Copy_of_PARTExtendedScrollViewer
            {
                get
                {
                    return _copy_of_partextendedscrollviewerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Copy_of_PARTExtendedScrollViewer item info.
            /// </summary>
            [RepositoryItemInfo("12d1d401-b97f-49c3-9199-cff18a9bbbfa")]
            public virtual RepoItemInfo Copy_of_PARTExtendedScrollViewerInfo
            {
                get
                {
                    return _copy_of_partextendedscrollviewerInfo;
                }
            }

            /// <summary>
            /// The Copy_of_ComboBox item.
            /// </summary>
            [RepositoryItem("4ac65433-920a-4eff-9536-7b3011e86f1a")]
            public virtual Ranorex.ComboBox Copy_of_ComboBox
            {
                get
                {
                    return _copy_of_comboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Copy_of_ComboBox item info.
            /// </summary>
            [RepositoryItemInfo("4ac65433-920a-4eff-9536-7b3011e86f1a")]
            public virtual RepoItemInfo Copy_of_ComboBoxInfo
            {
                get
                {
                    return _copy_of_comboboxInfo;
                }
            }

            /// <summary>
            /// The PARTUpdatesCheckOnScheduleCheck item.
            /// </summary>
            [RepositoryItem("d4089d2f-2954-4eaa-b766-325473d7ecea")]
            public virtual Ranorex.CheckBox PARTUpdatesCheckOnScheduleCheck
            {
                get
                {
                    return _partupdatescheckonschedulecheckInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The PARTUpdatesCheckOnScheduleCheck item info.
            /// </summary>
            [RepositoryItemInfo("d4089d2f-2954-4eaa-b766-325473d7ecea")]
            public virtual RepoItemInfo PARTUpdatesCheckOnScheduleCheckInfo
            {
                get
                {
                    return _partupdatescheckonschedulecheckInfo;
                }
            }

            /// <summary>
            /// The PARTContentHost item.
            /// </summary>
            [RepositoryItem("4c61107c-c64a-4d05-894c-fa9f30eee805")]
            public virtual Ranorex.Container PARTContentHost
            {
                get
                {
                    return _partcontenthostInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PARTContentHost item info.
            /// </summary>
            [RepositoryItemInfo("4c61107c-c64a-4d05-894c-fa9f30eee805")]
            public virtual RepoItemInfo PARTContentHostInfo
            {
                get
                {
                    return _partcontenthostInfo;
                }
            }

            /// <summary>
            /// The Save_Button item.
            /// </summary>
            [RepositoryItem("f64a5e52-9acc-4d2f-b8be-8570ff447d9d")]
            public virtual Ranorex.Button Save_Button
            {
                get
                {
                    return _save_buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Save_Button item info.
            /// </summary>
            [RepositoryItemInfo("f64a5e52-9acc-4d2f-b8be-8570ff447d9d")]
            public virtual RepoItemInfo Save_ButtonInfo
            {
                get
                {
                    return _save_buttonInfo;
                }
            }

            /// <summary>
            /// The Copy_of_Save_Button item.
            /// </summary>
            [RepositoryItem("33abaeda-ebaa-4d3a-ba7e-88401870f990")]
            public virtual Ranorex.Button Copy_of_Save_Button
            {
                get
                {
                    return _copy_of_save_buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Copy_of_Save_Button item info.
            /// </summary>
            [RepositoryItemInfo("33abaeda-ebaa-4d3a-ba7e-88401870f990")]
            public virtual RepoItemInfo Copy_of_Save_ButtonInfo
            {
                get
                {
                    return _copy_of_save_buttonInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("2ffac5df-a3c6-4978-9b1a-76ea0e207dd1")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("2ffac5df-a3c6-4978-9b1a-76ea0e207dd1")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Exit_Without_saving item.
            /// </summary>
            [RepositoryItem("4070c00e-f274-4313-ba46-8bb7579628f0")]
            public virtual Ranorex.Button Exit_Without_saving
            {
                get
                {
                    return _exit_without_savingInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Exit_Without_saving item info.
            /// </summary>
            [RepositoryItemInfo("4070c00e-f274-4313-ba46-8bb7579628f0")]
            public virtual RepoItemInfo Exit_Without_savingInfo
            {
                get
                {
                    return _exit_without_savingInfo;
                }
            }

            /// <summary>
            /// The ComboBox2 item.
            /// </summary>
            [RepositoryItem("edbd935c-5039-4e08-a6cd-7370ce00e9c9")]
            public virtual Ranorex.ComboBox ComboBox2
            {
                get
                {
                    return _combobox2Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox2 item info.
            /// </summary>
            [RepositoryItemInfo("edbd935c-5039-4e08-a6cd-7370ce00e9c9")]
            public virtual RepoItemInfo ComboBox2Info
            {
                get
                {
                    return _combobox2Info;
                }
            }

            /// <summary>
            /// The Thumb item.
            /// </summary>
            [RepositoryItem("d4254311-ea66-4c7e-ba29-a7707261454e")]
            public virtual Ranorex.Indicator Thumb
            {
                get
                {
                    return _thumbInfo.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The Thumb item info.
            /// </summary>
            [RepositoryItemInfo("d4254311-ea66-4c7e-ba29-a7707261454e")]
            public virtual RepoItemInfo ThumbInfo
            {
                get
                {
                    return _thumbInfo;
                }
            }

            /// <summary>
            /// The PARTPositiveButton item.
            /// </summary>
            [RepositoryItem("2d47b80d-5978-42ac-8d5b-be30c80a8977")]
            public virtual Ranorex.Button PARTPositiveButton
            {
                get
                {
                    return _partpositivebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTPositiveButton item info.
            /// </summary>
            [RepositoryItemInfo("2d47b80d-5978-42ac-8d5b-be30c80a8977")]
            public virtual RepoItemInfo PARTPositiveButtonInfo
            {
                get
                {
                    return _partpositivebuttonInfo;
                }
            }

            /// <summary>
            /// The MenuAutomationIdsInstrumentAction item.
            /// </summary>
            [RepositoryItem("e19bb8af-e919-40ef-b637-0283ccb77672")]
            public virtual Ranorex.MenuItem MenuAutomationIdsInstrumentAction
            {
                get
                {
                    return _menuautomationidsinstrumentactionInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuAutomationIdsInstrumentAction item info.
            /// </summary>
            [RepositoryItemInfo("e19bb8af-e919-40ef-b637-0283ccb77672")]
            public virtual RepoItemInfo MenuAutomationIdsInstrumentActionInfo
            {
                get
                {
                    return _menuautomationidsinstrumentactionInfo;
                }
            }

            /// <summary>
            /// The MenuAutomationIdsViewAction item.
            /// </summary>
            [RepositoryItem("1fec0964-ddd2-425d-a0b4-db883956abf4")]
            public virtual Ranorex.MenuItem MenuAutomationIdsViewAction
            {
                get
                {
                    return _menuautomationidsviewactionInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuAutomationIdsViewAction item info.
            /// </summary>
            [RepositoryItemInfo("1fec0964-ddd2-425d-a0b4-db883956abf4")]
            public virtual RepoItemInfo MenuAutomationIdsViewActionInfo
            {
                get
                {
                    return _menuautomationidsviewactionInfo;
                }
            }

            /// <summary>
            /// The Back_Button item.
            /// </summary>
            [RepositoryItem("359ff0df-5289-444a-82f1-faa5b98448bc")]
            public virtual Ranorex.Button Back_Button
            {
                get
                {
                    return _back_buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Back_Button item info.
            /// </summary>
            [RepositoryItemInfo("359ff0df-5289-444a-82f1-faa5b98448bc")]
            public virtual RepoItemInfo Back_ButtonInfo
            {
                get
                {
                    return _back_buttonInfo;
                }
            }

            /// <summary>
            /// The ListBox item.
            /// </summary>
            [RepositoryItem("27b251af-b1d9-4334-9265-84fc0fdb69c5")]
            public virtual Ranorex.List ListBox
            {
                get
                {
                    return _listboxInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The ListBox item info.
            /// </summary>
            [RepositoryItemInfo("27b251af-b1d9-4334-9265-84fc0fdb69c5")]
            public virtual RepoItemInfo ListBoxInfo
            {
                get
                {
                    return _listboxInfo;
                }
            }

            /// <summary>
            /// The BiModal_RadioButton item.
            /// </summary>
            [RepositoryItem("a4647678-c87a-44ac-bb94-1dd50d933487")]
            public virtual Ranorex.Button BiModal_RadioButton
            {
                get
                {
                    return _bimodal_radiobuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BiModal_RadioButton item info.
            /// </summary>
            [RepositoryItemInfo("a4647678-c87a-44ac-bb94-1dd50d933487")]
            public virtual RepoItemInfo BiModal_RadioButtonInfo
            {
                get
                {
                    return _bimodal_radiobuttonInfo;
                }
            }

            /// <summary>
            /// The DialogAutomationIdsPositiveAction item.
            /// </summary>
            [RepositoryItem("6c13bf68-24ff-4dc9-b6cd-bced76f9ce9a")]
            public virtual Ranorex.Button DialogAutomationIdsPositiveAction
            {
                get
                {
                    return _dialogautomationidspositiveactionInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DialogAutomationIdsPositiveAction item info.
            /// </summary>
            [RepositoryItemInfo("6c13bf68-24ff-4dc9-b6cd-bced76f9ce9a")]
            public virtual RepoItemInfo DialogAutomationIdsPositiveActionInfo
            {
                get
                {
                    return _dialogautomationidspositiveactionInfo;
                }
            }

            /// <summary>
            /// The Copy_of_ComboBox2 item.
            /// </summary>
            [RepositoryItem("d7b1b1bc-2c4c-43a6-b2eb-f71f16b0ba3a")]
            public virtual Ranorex.ComboBox Copy_of_ComboBox2
            {
                get
                {
                    return _copy_of_combobox2Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Copy_of_ComboBox2 item info.
            /// </summary>
            [RepositoryItemInfo("d7b1b1bc-2c4c-43a6-b2eb-f71f16b0ba3a")]
            public virtual RepoItemInfo Copy_of_ComboBox2Info
            {
                get
                {
                    return _copy_of_combobox2Info;
                }
            }

            /// <summary>
            /// The Copy_of_PARTContentHost item.
            /// </summary>
            [RepositoryItem("ad3eb913-f5a7-4901-8087-abe48e16e01e")]
            public virtual Ranorex.Text Copy_of_PARTContentHost
            {
                get
                {
                    return _copy_of_partcontenthostInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Copy_of_PARTContentHost item info.
            /// </summary>
            [RepositoryItemInfo("ad3eb913-f5a7-4901-8087-abe48e16e01e")]
            public virtual RepoItemInfo Copy_of_PARTContentHostInfo
            {
                get
                {
                    return _copy_of_partcontenthostInfo;
                }
            }

            /// <summary>
            /// The ModeloDoAparelho item.
            /// </summary>
            [RepositoryItem("ffbd9d41-25e8-4fee-a119-932c8fb3a27c")]
            public virtual Ranorex.Text ModeloDoAparelho
            {
                get
                {
                    return _modelodoaparelhoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ModeloDoAparelho item info.
            /// </summary>
            [RepositoryItemInfo("ffbd9d41-25e8-4fee-a119-932c8fb3a27c")]
            public virtual RepoItemInfo ModeloDoAparelhoInfo
            {
                get
                {
                    return _modelodoaparelhoInfo;
                }
            }
        }

        /// <summary>
        /// The SmartFitAppFolder folder.
        /// </summary>
        [RepositoryFolder("294f7592-db9b-4ca5-8893-1fac816191d2")]
        public partial class SmartFitAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _preferencesInfo;
            RepoItemInfo _preferences_listInfo;
            RepoItemInfo _copy_of_preferences_listInfo;
            RepoItemInfo _copy_of_copy_of_preferences_listInfo;
            RepoItemInfo _partobjectnametextblockInfo;
            RepoItemInfo _connectionautomationidscommunicationintInfo;

            /// <summary>
            /// Creates a new SmartFit  folder.
            /// </summary>
            public SmartFitAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SmartFit", "/contextmenu[@processname='SmartFit' or @processname='SolusMax' and @win32ownerwindowlevel='1']", parentFolder, 30000, null, false, "294f7592-db9b-4ca5-8893-1fac816191d2", "")
            {
                _preferencesInfo = new RepoItemInfo(this, "Preferences", "menuitem[@text='Preferences']", 30000, null, "02344485-f9d2-48b2-be38-1f523c2c82fd");
                _preferences_listInfo = new RepoItemInfo(this, "Preferences_list", "menuitem[8]", 30000, null, "5e169253-c7fa-4f27-8de7-6960770d2bf8");
                _copy_of_preferences_listInfo = new RepoItemInfo(this, "Copy_of_Preferences_list", "menuitem[3]", 30000, null, "51e4a980-dcbd-41d2-b531-c3e37bc903d6");
                _copy_of_copy_of_preferences_listInfo = new RepoItemInfo(this, "Copy_of_Copy_of_Preferences_list", "menuitem[1]", 30000, null, "2e3c08fa-131f-4b17-b108-0a91f4fa1dee");
                _partobjectnametextblockInfo = new RepoItemInfo(this, "PARTObjectNameTextBlock", "menuitem[@automationid='MenuAutomationIds.ViewAutomationIds.LanguageAction']/?/?/text[@automationid='PART_ObjectNameTextBlock']", 30000, null, "29746659-35eb-4060-b834-b48e43bcb8b0");
                _connectionautomationidscommunicationintInfo = new RepoItemInfo(this, "ConnectionAutomationIdsCommunicationInt", "listitem[@automationid='ConnectionAutomationIds.CommunicationInterfaceItemsAutomationIds.SpeedLink']", 30000, null, "36e01efc-0f6d-4f7c-b5c8-68eee25900e0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("294f7592-db9b-4ca5-8893-1fac816191d2")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("294f7592-db9b-4ca5-8893-1fac816191d2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Preferences item.
            /// </summary>
            [RepositoryItem("02344485-f9d2-48b2-be38-1f523c2c82fd")]
            public virtual Ranorex.MenuItem Preferences
            {
                get
                {
                    return _preferencesInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Preferences item info.
            /// </summary>
            [RepositoryItemInfo("02344485-f9d2-48b2-be38-1f523c2c82fd")]
            public virtual RepoItemInfo PreferencesInfo
            {
                get
                {
                    return _preferencesInfo;
                }
            }

            /// <summary>
            /// The Preferences_list item.
            /// </summary>
            [RepositoryItem("5e169253-c7fa-4f27-8de7-6960770d2bf8")]
            public virtual Ranorex.MenuItem Preferences_list
            {
                get
                {
                    return _preferences_listInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Preferences_list item info.
            /// </summary>
            [RepositoryItemInfo("5e169253-c7fa-4f27-8de7-6960770d2bf8")]
            public virtual RepoItemInfo Preferences_listInfo
            {
                get
                {
                    return _preferences_listInfo;
                }
            }

            /// <summary>
            /// The Copy_of_Preferences_list item.
            /// </summary>
            [RepositoryItem("51e4a980-dcbd-41d2-b531-c3e37bc903d6")]
            public virtual Ranorex.MenuItem Copy_of_Preferences_list
            {
                get
                {
                    return _copy_of_preferences_listInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Copy_of_Preferences_list item info.
            /// </summary>
            [RepositoryItemInfo("51e4a980-dcbd-41d2-b531-c3e37bc903d6")]
            public virtual RepoItemInfo Copy_of_Preferences_listInfo
            {
                get
                {
                    return _copy_of_preferences_listInfo;
                }
            }

            /// <summary>
            /// The Copy_of_Copy_of_Preferences_list item.
            /// </summary>
            [RepositoryItem("2e3c08fa-131f-4b17-b108-0a91f4fa1dee")]
            public virtual Ranorex.MenuItem Copy_of_Copy_of_Preferences_list
            {
                get
                {
                    return _copy_of_copy_of_preferences_listInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Copy_of_Copy_of_Preferences_list item info.
            /// </summary>
            [RepositoryItemInfo("2e3c08fa-131f-4b17-b108-0a91f4fa1dee")]
            public virtual RepoItemInfo Copy_of_Copy_of_Preferences_listInfo
            {
                get
                {
                    return _copy_of_copy_of_preferences_listInfo;
                }
            }

            /// <summary>
            /// The PARTObjectNameTextBlock item.
            /// </summary>
            [RepositoryItem("29746659-35eb-4060-b834-b48e43bcb8b0")]
            public virtual Ranorex.Text PARTObjectNameTextBlock
            {
                get
                {
                    return _partobjectnametextblockInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PARTObjectNameTextBlock item info.
            /// </summary>
            [RepositoryItemInfo("29746659-35eb-4060-b834-b48e43bcb8b0")]
            public virtual RepoItemInfo PARTObjectNameTextBlockInfo
            {
                get
                {
                    return _partobjectnametextblockInfo;
                }
            }

            /// <summary>
            /// The ConnectionAutomationIdsCommunicationInt item.
            /// </summary>
            [RepositoryItem("36e01efc-0f6d-4f7c-b5c8-68eee25900e0")]
            public virtual Ranorex.ListItem ConnectionAutomationIdsCommunicationInt
            {
                get
                {
                    return _connectionautomationidscommunicationintInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ConnectionAutomationIdsCommunicationInt item info.
            /// </summary>
            [RepositoryItemInfo("36e01efc-0f6d-4f7c-b5c8-68eee25900e0")]
            public virtual RepoItemInfo ConnectionAutomationIdsCommunicationIntInfo
            {
                get
                {
                    return _connectionautomationidscommunicationintInfo;
                }
            }
        }

        /// <summary>
        /// The FSWModule_RepoAppFolder folder.
        /// </summary>
        [RepositoryFolder("620b9651-d9f6-4556-bca4-7f2bf50b57e3")]
        public partial class FSWModule_RepoAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _instrument_selection_textboxInfo;
            RepoItemInfo _remove_buttonInfo;
            RepoItemInfo _simulate_buttonInfo;
            RepoItemInfo _partcontinuebuttonInfo;
            RepoItemInfo _navigationautomationidsmainautomationidInfo;
            RepoItemInfo _editInfo;
            RepoItemInfo _bearbeiten1Info;
            RepoItemInfo _statemachineautomationidscontinueactionInfo;
            RepoItemInfo _parthamburgertoggleInfo;
            RepoItemInfo _x_buttonInfo;
            RepoItemInfo _fittingInfo;
            RepoItemInfo _connectionautomationidscommunicationintInfo;
            RepoItemInfo _connectionautomationidsconnectactionInfo;

            /// <summary>
            /// Creates a new FSWModule_Repo  folder.
            /// </summary>
            public FSWModule_RepoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FSWModule_Repo", "/form[@name~'Smart Fit' or @name~'Launcher' or @name~'Solus Max' or @name~'Interton Fitting' or @name~'Audigy' or @name~'Costco' or @name~'amplifon' or @classname='Window']", parentFolder, 30000, null, false, "620b9651-d9f6-4556-bca4-7f2bf50b57e3", "")
            {
                _instrument_selection_textboxInfo = new RepoItemInfo(this, "Instrument_Selection_Textbox", "text", 30000, null, "8978bc6f-8cff-4854-84e0-84f2f65d2f13");
                _remove_buttonInfo = new RepoItemInfo(this, "Remove_Button", "button[4]", 30000, null, "2141f5d5-4c3d-4a5e-8465-e57448b6cd35");
                _simulate_buttonInfo = new RepoItemInfo(this, "Simulate_Button", "button[10]", 30000, null, "9d1463cf-08a3-44b0-9f88-ff471fda8b84");
                _partcontinuebuttonInfo = new RepoItemInfo(this, "PARTContinueButton", "button[@automationid='PART_ContinueButton' or @automationid='StateMachineAutomationIds.ContinueAction']", 30000, null, "ebd271fd-2f23-4517-bd80-a3aebb790f6d");
                _navigationautomationidsmainautomationidInfo = new RepoItemInfo(this, "NavigationAutomationIdsMainAutomationId", "list[2]/listitem/radiobutton[@automationid='NavigationAutomationIds.MainAutomationIds.Fitting']", 30000, null, "7a354002-83e2-40d1-b93d-67815b6997dd");
                _editInfo = new RepoItemInfo(this, "Edit", "contextmenu/menuitem[2]", 30000, null, "9714a48d-6f40-4501-b58f-f0e64f626b63");
                _bearbeiten1Info = new RepoItemInfo(this, "Bearbeiten1", "?/?/menuitem[@name='Bearbeiten']", 30000, null, "519666a6-0def-4f80-b494-088ce24c2bef");
                _statemachineautomationidscontinueactionInfo = new RepoItemInfo(this, "StateMachineAutomationIdsContinueAction", "button[@automationid='StateMachineAutomationIds.ContinueAction']", 30000, null, "a174b380-513c-499d-aea1-7e414a4ce6a2");
                _parthamburgertoggleInfo = new RepoItemInfo(this, "PARTHamburgerToggle", "button[@automationid='PART_HamburgerToggle']", 30000, null, "6b45e483-8a57-49ff-860e-8a6bd5b30a7a");
                _x_buttonInfo = new RepoItemInfo(this, "X_Button", "button[@automationid='WindowAutomationIds.CloseAction']", 30000, null, "0a662879-1b2f-44bc-a1ce-c68cce30f11a");
                _fittingInfo = new RepoItemInfo(this, "Fitting", "list/listitem[@name='Fitting']", 30000, null, "3085e9cc-925a-4830-b3ed-069ea40f9ea0");
                _connectionautomationidscommunicationintInfo = new RepoItemInfo(this, "ConnectionAutomationIdsCommunicationInt", "combobox[@automationid='ConnectionAutomationIds.CommunicationInterfaceItems']", 30000, null, "98e09cbc-8dca-4952-8002-1432a19d48b6");
                _connectionautomationidsconnectactionInfo = new RepoItemInfo(this, "ConnectionAutomationIdsConnectAction", "button[@automationid='ConnectionAutomationIds.ConnectAction']", 30000, null, "d2e60fd2-d5e5-44bb-9a4e-2473d3b569fa");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("620b9651-d9f6-4556-bca4-7f2bf50b57e3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("620b9651-d9f6-4556-bca4-7f2bf50b57e3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Instrument_Selection_Textbox item.
            /// </summary>
            [RepositoryItem("8978bc6f-8cff-4854-84e0-84f2f65d2f13")]
            public virtual Ranorex.Text Instrument_Selection_Textbox
            {
                get
                {
                    return _instrument_selection_textboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Instrument_Selection_Textbox item info.
            /// </summary>
            [RepositoryItemInfo("8978bc6f-8cff-4854-84e0-84f2f65d2f13")]
            public virtual RepoItemInfo Instrument_Selection_TextboxInfo
            {
                get
                {
                    return _instrument_selection_textboxInfo;
                }
            }

            /// <summary>
            /// The Remove_Button item.
            /// </summary>
            [RepositoryItem("2141f5d5-4c3d-4a5e-8465-e57448b6cd35")]
            public virtual Ranorex.Button Remove_Button
            {
                get
                {
                    return _remove_buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Remove_Button item info.
            /// </summary>
            [RepositoryItemInfo("2141f5d5-4c3d-4a5e-8465-e57448b6cd35")]
            public virtual RepoItemInfo Remove_ButtonInfo
            {
                get
                {
                    return _remove_buttonInfo;
                }
            }

            /// <summary>
            /// The Simulate_Button item.
            /// </summary>
            [RepositoryItem("9d1463cf-08a3-44b0-9f88-ff471fda8b84")]
            public virtual Ranorex.Button Simulate_Button
            {
                get
                {
                    return _simulate_buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Simulate_Button item info.
            /// </summary>
            [RepositoryItemInfo("9d1463cf-08a3-44b0-9f88-ff471fda8b84")]
            public virtual RepoItemInfo Simulate_ButtonInfo
            {
                get
                {
                    return _simulate_buttonInfo;
                }
            }

            /// <summary>
            /// The PARTContinueButton item.
            /// </summary>
            [RepositoryItem("ebd271fd-2f23-4517-bd80-a3aebb790f6d")]
            public virtual Ranorex.Button PARTContinueButton
            {
                get
                {
                    return _partcontinuebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTContinueButton item info.
            /// </summary>
            [RepositoryItemInfo("ebd271fd-2f23-4517-bd80-a3aebb790f6d")]
            public virtual RepoItemInfo PARTContinueButtonInfo
            {
                get
                {
                    return _partcontinuebuttonInfo;
                }
            }

            /// <summary>
            /// The NavigationAutomationIdsMainAutomationId item.
            /// </summary>
            [RepositoryItem("7a354002-83e2-40d1-b93d-67815b6997dd")]
            public virtual Ranorex.RadioButton NavigationAutomationIdsMainAutomationId
            {
                get
                {
                    return _navigationautomationidsmainautomationidInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The NavigationAutomationIdsMainAutomationId item info.
            /// </summary>
            [RepositoryItemInfo("7a354002-83e2-40d1-b93d-67815b6997dd")]
            public virtual RepoItemInfo NavigationAutomationIdsMainAutomationIdInfo
            {
                get
                {
                    return _navigationautomationidsmainautomationidInfo;
                }
            }

            /// <summary>
            /// The Edit item.
            /// </summary>
            [RepositoryItem("9714a48d-6f40-4501-b58f-f0e64f626b63")]
            public virtual Ranorex.MenuItem Edit
            {
                get
                {
                    return _editInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Edit item info.
            /// </summary>
            [RepositoryItemInfo("9714a48d-6f40-4501-b58f-f0e64f626b63")]
            public virtual RepoItemInfo EditInfo
            {
                get
                {
                    return _editInfo;
                }
            }

            /// <summary>
            /// The Bearbeiten1 item.
            /// </summary>
            [RepositoryItem("519666a6-0def-4f80-b494-088ce24c2bef")]
            public virtual Ranorex.MenuItem Bearbeiten1
            {
                get
                {
                    return _bearbeiten1Info.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Bearbeiten1 item info.
            /// </summary>
            [RepositoryItemInfo("519666a6-0def-4f80-b494-088ce24c2bef")]
            public virtual RepoItemInfo Bearbeiten1Info
            {
                get
                {
                    return _bearbeiten1Info;
                }
            }

            /// <summary>
            /// The StateMachineAutomationIdsContinueAction item.
            /// </summary>
            [RepositoryItem("a174b380-513c-499d-aea1-7e414a4ce6a2")]
            public virtual Ranorex.Button StateMachineAutomationIdsContinueAction
            {
                get
                {
                    return _statemachineautomationidscontinueactionInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The StateMachineAutomationIdsContinueAction item info.
            /// </summary>
            [RepositoryItemInfo("a174b380-513c-499d-aea1-7e414a4ce6a2")]
            public virtual RepoItemInfo StateMachineAutomationIdsContinueActionInfo
            {
                get
                {
                    return _statemachineautomationidscontinueactionInfo;
                }
            }

            /// <summary>
            /// The PARTHamburgerToggle item.
            /// </summary>
            [RepositoryItem("6b45e483-8a57-49ff-860e-8a6bd5b30a7a")]
            public virtual Ranorex.Button PARTHamburgerToggle
            {
                get
                {
                    return _parthamburgertoggleInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTHamburgerToggle item info.
            /// </summary>
            [RepositoryItemInfo("6b45e483-8a57-49ff-860e-8a6bd5b30a7a")]
            public virtual RepoItemInfo PARTHamburgerToggleInfo
            {
                get
                {
                    return _parthamburgertoggleInfo;
                }
            }

            /// <summary>
            /// The X_Button item.
            /// </summary>
            [RepositoryItem("0a662879-1b2f-44bc-a1ce-c68cce30f11a")]
            public virtual Ranorex.Button X_Button
            {
                get
                {
                    return _x_buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The X_Button item info.
            /// </summary>
            [RepositoryItemInfo("0a662879-1b2f-44bc-a1ce-c68cce30f11a")]
            public virtual RepoItemInfo X_ButtonInfo
            {
                get
                {
                    return _x_buttonInfo;
                }
            }

            /// <summary>
            /// The Fitting item.
            /// </summary>
            [RepositoryItem("3085e9cc-925a-4830-b3ed-069ea40f9ea0")]
            public virtual Ranorex.ListItem Fitting
            {
                get
                {
                    return _fittingInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Fitting item info.
            /// </summary>
            [RepositoryItemInfo("3085e9cc-925a-4830-b3ed-069ea40f9ea0")]
            public virtual RepoItemInfo FittingInfo
            {
                get
                {
                    return _fittingInfo;
                }
            }

            /// <summary>
            /// The ConnectionAutomationIdsCommunicationInt item.
            /// </summary>
            [RepositoryItem("98e09cbc-8dca-4952-8002-1432a19d48b6")]
            public virtual Ranorex.ComboBox ConnectionAutomationIdsCommunicationInt
            {
                get
                {
                    return _connectionautomationidscommunicationintInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ConnectionAutomationIdsCommunicationInt item info.
            /// </summary>
            [RepositoryItemInfo("98e09cbc-8dca-4952-8002-1432a19d48b6")]
            public virtual RepoItemInfo ConnectionAutomationIdsCommunicationIntInfo
            {
                get
                {
                    return _connectionautomationidscommunicationintInfo;
                }
            }

            /// <summary>
            /// The ConnectionAutomationIdsConnectAction item.
            /// </summary>
            [RepositoryItem("d2e60fd2-d5e5-44bb-9a4e-2473d3b569fa")]
            public virtual Ranorex.Button ConnectionAutomationIdsConnectAction
            {
                get
                {
                    return _connectionautomationidsconnectactionInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ConnectionAutomationIdsConnectAction item info.
            /// </summary>
            [RepositoryItemInfo("d2e60fd2-d5e5-44bb-9a4e-2473d3b569fa")]
            public virtual RepoItemInfo ConnectionAutomationIdsConnectActionInfo
            {
                get
                {
                    return _connectionautomationidsconnectactionInfo;
                }
            }
        }

        /// <summary>
        /// The PopupAppFolder folder.
        /// </summary>
        [RepositoryFolder("c1a0e544-e3de-4322-8b9f-b04d4735c7d2")]
        public partial class PopupAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _somelistitemInfo;
            RepoItemInfo _scrollviewerInfo;
            RepoItemInfo _thumbInfo;
            RepoItemInfo _partupleftrepeatbuttonInfo;

            /// <summary>
            /// Creates a new Popup  folder.
            /// </summary>
            public PopupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Popup", "/form[@classname='Popup' and @orientation='None' and @processname='SmartFit']", parentFolder, 30000, null, false, "c1a0e544-e3de-4322-8b9f-b04d4735c7d2", "")
            {
                _somelistitemInfo = new RepoItemInfo(this, "SomeListItem", "container/listitem[1]", 30000, null, "d76b706d-913f-43e5-8295-abd6b7ed0e10");
                _scrollviewerInfo = new RepoItemInfo(this, "ScrollViewer", "container[@classname='ScrollViewer']", 30000, null, "95f499cf-4def-45cd-a58f-10784f8c440a");
                _thumbInfo = new RepoItemInfo(this, "Thumb", "?/?/scrollbar[@automationid='VerticalScrollBar']/indicator[@classname='Thumb']", 30000, null, "3978055a-eee6-46b5-abf2-426467faf287");
                _partupleftrepeatbuttonInfo = new RepoItemInfo(this, "PARTUpLeftRepeatButton", "?/?/scrollbar[@automationid='VerticalScrollBar']/button[@automationid='PART_UpLeftRepeatButton']", 30000, null, "b9c135b8-bb50-4039-b456-838c65814ce7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c1a0e544-e3de-4322-8b9f-b04d4735c7d2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c1a0e544-e3de-4322-8b9f-b04d4735c7d2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeListItem item.
            /// </summary>
            [RepositoryItem("d76b706d-913f-43e5-8295-abd6b7ed0e10")]
            public virtual Ranorex.ListItem SomeListItem
            {
                get
                {
                    return _somelistitemInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SomeListItem item info.
            /// </summary>
            [RepositoryItemInfo("d76b706d-913f-43e5-8295-abd6b7ed0e10")]
            public virtual RepoItemInfo SomeListItemInfo
            {
                get
                {
                    return _somelistitemInfo;
                }
            }

            /// <summary>
            /// The ScrollViewer item.
            /// </summary>
            [RepositoryItem("95f499cf-4def-45cd-a58f-10784f8c440a")]
            public virtual Ranorex.Container ScrollViewer
            {
                get
                {
                    return _scrollviewerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ScrollViewer item info.
            /// </summary>
            [RepositoryItemInfo("95f499cf-4def-45cd-a58f-10784f8c440a")]
            public virtual RepoItemInfo ScrollViewerInfo
            {
                get
                {
                    return _scrollviewerInfo;
                }
            }

            /// <summary>
            /// The Thumb item.
            /// </summary>
            [RepositoryItem("3978055a-eee6-46b5-abf2-426467faf287")]
            public virtual Ranorex.Indicator Thumb
            {
                get
                {
                    return _thumbInfo.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The Thumb item info.
            /// </summary>
            [RepositoryItemInfo("3978055a-eee6-46b5-abf2-426467faf287")]
            public virtual RepoItemInfo ThumbInfo
            {
                get
                {
                    return _thumbInfo;
                }
            }

            /// <summary>
            /// The PARTUpLeftRepeatButton item.
            /// </summary>
            [RepositoryItem("b9c135b8-bb50-4039-b456-838c65814ce7")]
            public virtual Ranorex.Button PARTUpLeftRepeatButton
            {
                get
                {
                    return _partupleftrepeatbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTUpLeftRepeatButton item info.
            /// </summary>
            [RepositoryItemInfo("b9c135b8-bb50-4039-b456-838c65814ce7")]
            public virtual RepoItemInfo PARTUpLeftRepeatButtonInfo
            {
                get
                {
                    return _partupleftrepeatbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The SmartFit15InstallShieldWizardAppFolder folder.
        /// </summary>
        [RepositoryFolder("b930523e-1185-4175-bb43-7b0ce14587db")]
        public partial class SmartFit15InstallShieldWizardAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _buttonnextInfo;
            RepoItemInfo _iacceptthetermsinthelicenseagreemInfo;
            RepoItemInfo _checkboxstandaloneInfo;
            RepoItemInfo _combobox17451Info;
            RepoItemInfo _buttoninstallInfo;
            RepoItemInfo _buttonfinishInfo;
            RepoItemInfo _menuautomationidsfittingactionInfo;
            RepoItemInfo _menuautomationidshelpactionInfo;
            RepoItemInfo _menuautomationidshelpaction1Info;
            RepoItemInfo _menuautomationidseditactionInfo;
            RepoItemInfo _navigationautomationidsmainautomationidInfo;
            RepoItemInfo _navigationautomationidsmainautomationid1Info;
            RepoItemInfo _text65535Info;
            RepoItemInfo _buttonok1Info;
            RepoItemInfo _cancelInfo;
            RepoItemInfo _listboxInfo;

            /// <summary>
            /// Creates a new SmartFit15InstallShieldWizard  folder.
            /// </summary>
            public SmartFit15InstallShieldWizardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SmartFit15InstallShieldWizard", "/form[@title~'Smart Fit' or @title~'Solus Max' or @title~'Audigy']", parentFolder, 30000, null, false, "b930523e-1185-4175-bb43-7b0ce14587db", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='&OK']", 30000, null, "8c0989be-eba7-4328-86fc-b65eb68cd2f2");
                _buttonnextInfo = new RepoItemInfo(this, "ButtonNext", "button[@text='&Next >']", 30000, null, "a5bab444-3a7a-47d6-9df3-46262fafe89b");
                _iacceptthetermsinthelicenseagreemInfo = new RepoItemInfo(this, "IAcceptTheTermsInTheLicenseAgreem", "?/?/radiobutton[@text>'I &accept the terms in the']", 30000, null, "39c741a5-3790-4be4-a233-39809c3e81e3");
                _checkboxstandaloneInfo = new RepoItemInfo(this, "CheckBoxStandalone", "checkbox[@text='&Standalone']", 30000, null, "00851c57-dea2-4327-a3ff-a2aa726e3d1e");
                _combobox17451Info = new RepoItemInfo(this, "ComboBox17451", "combobox[@class='ComboBox']", 30000, null, "9bf5c15c-caf3-4085-811e-d11ccbc2c0aa");
                _buttoninstallInfo = new RepoItemInfo(this, "ButtonInstall", "button[@text='&Install']", 30000, null, "64c741fd-8e1b-41f6-830f-5456a42904df");
                _buttonfinishInfo = new RepoItemInfo(this, "ButtonFinish", "button[@text='&Finish']", 600000, null, "5656e623-e1d6-41f0-804d-2c7609d79c6d");
                _menuautomationidsfittingactionInfo = new RepoItemInfo(this, "MenuAutomationIdsFittingAction", "?/?/menuitem[@automationid='MenuAutomationIds.FittingAction']", 30000, null, "5ecb5f89-0a58-4f91-bbd9-6dd9c3e2e2c6");
                _menuautomationidshelpactionInfo = new RepoItemInfo(this, "MenuAutomationIdsHelpAction", "contextmenu/menuitem[@automationid='MenuAutomationIds.HelpAction']", 30000, null, "afc185ef-fed1-4f6e-83c7-290429ae75f7");
                _menuautomationidshelpaction1Info = new RepoItemInfo(this, "MenuAutomationIdsHelpAction1", "?/?/menuitem[@automationid='MenuAutomationIds.HelpAction']", 30000, null, "9f9d1ad9-228d-4bac-ba9b-e2961856a12c");
                _menuautomationidseditactionInfo = new RepoItemInfo(this, "MenuAutomationIdsEditAction", "?/?/menuitem[@automationid='MenuAutomationIds.EditAction']", 30000, null, "de7bcafb-68a4-4b4d-b31e-3b841cc41f36");
                _navigationautomationidsmainautomationidInfo = new RepoItemInfo(this, "NavigationAutomationIdsMainAutomationId", "list[2]/?/?/radiobutton[@automationid='NavigationAutomationIds.MainAutomationIds.Fitting']", 30000, null, "5c86eeca-14b8-42b8-a248-d36a22199902");
                _navigationautomationidsmainautomationid1Info = new RepoItemInfo(this, "NavigationAutomationIdsMainAutomationId1", "list[2]/?/?/radiobutton[@automationid='NavigationAutomationIds.MainAutomationIds.FittingAutomationIds.GainAdustments']", 30000, null, "ce36667b-1420-452c-966c-d012302c444c");
                _text65535Info = new RepoItemInfo(this, "Text65535", "text[@windowtext='A newer or same version of this application is already installed on this computer. If you wish to install this version, please uninstall the installed version first.']", 30000, null, "dce81d72-c118-4262-8957-afa498314810");
                _buttonok1Info = new RepoItemInfo(this, "ButtonOK1", "button[@text='OK']", 30000, null, "56600c0f-cc40-4148-91ca-157bbb71057e");
                _cancelInfo = new RepoItemInfo(this, "Cancel", "button[@text='Cancel']", 30000, null, "deaf3d12-ae16-4220-8313-5b9d3f6f3c90");
                _listboxInfo = new RepoItemInfo(this, "ListBox", "container[@automationid='PART_ExtendedScrollViewer']/list[3]", 30000, null, "fbcb05d9-3b45-4752-8040-0baa68128a3c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b930523e-1185-4175-bb43-7b0ce14587db")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b930523e-1185-4175-bb43-7b0ce14587db")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("8c0989be-eba7-4328-86fc-b65eb68cd2f2")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("8c0989be-eba7-4328-86fc-b65eb68cd2f2")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The ButtonNext item.
            /// </summary>
            [RepositoryItem("a5bab444-3a7a-47d6-9df3-46262fafe89b")]
            public virtual Ranorex.Button ButtonNext
            {
                get
                {
                    return _buttonnextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNext item info.
            /// </summary>
            [RepositoryItemInfo("a5bab444-3a7a-47d6-9df3-46262fafe89b")]
            public virtual RepoItemInfo ButtonNextInfo
            {
                get
                {
                    return _buttonnextInfo;
                }
            }

            /// <summary>
            /// The IAcceptTheTermsInTheLicenseAgreem item.
            /// </summary>
            [RepositoryItem("39c741a5-3790-4be4-a233-39809c3e81e3")]
            public virtual Ranorex.RadioButton IAcceptTheTermsInTheLicenseAgreem
            {
                get
                {
                    return _iacceptthetermsinthelicenseagreemInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The IAcceptTheTermsInTheLicenseAgreem item info.
            /// </summary>
            [RepositoryItemInfo("39c741a5-3790-4be4-a233-39809c3e81e3")]
            public virtual RepoItemInfo IAcceptTheTermsInTheLicenseAgreemInfo
            {
                get
                {
                    return _iacceptthetermsinthelicenseagreemInfo;
                }
            }

            /// <summary>
            /// The CheckBoxStandalone item.
            /// </summary>
            [RepositoryItem("00851c57-dea2-4327-a3ff-a2aa726e3d1e")]
            public virtual Ranorex.CheckBox CheckBoxStandalone
            {
                get
                {
                    return _checkboxstandaloneInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CheckBoxStandalone item info.
            /// </summary>
            [RepositoryItemInfo("00851c57-dea2-4327-a3ff-a2aa726e3d1e")]
            public virtual RepoItemInfo CheckBoxStandaloneInfo
            {
                get
                {
                    return _checkboxstandaloneInfo;
                }
            }

            /// <summary>
            /// The ComboBox17451 item.
            /// </summary>
            [RepositoryItem("9bf5c15c-caf3-4085-811e-d11ccbc2c0aa")]
            public virtual Ranorex.ComboBox ComboBox17451
            {
                get
                {
                    return _combobox17451Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox17451 item info.
            /// </summary>
            [RepositoryItemInfo("9bf5c15c-caf3-4085-811e-d11ccbc2c0aa")]
            public virtual RepoItemInfo ComboBox17451Info
            {
                get
                {
                    return _combobox17451Info;
                }
            }

            /// <summary>
            /// The ButtonInstall item.
            /// </summary>
            [RepositoryItem("64c741fd-8e1b-41f6-830f-5456a42904df")]
            public virtual Ranorex.Button ButtonInstall
            {
                get
                {
                    return _buttoninstallInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonInstall item info.
            /// </summary>
            [RepositoryItemInfo("64c741fd-8e1b-41f6-830f-5456a42904df")]
            public virtual RepoItemInfo ButtonInstallInfo
            {
                get
                {
                    return _buttoninstallInfo;
                }
            }

            /// <summary>
            /// The ButtonFinish item.
            /// </summary>
            [RepositoryItem("5656e623-e1d6-41f0-804d-2c7609d79c6d")]
            public virtual Ranorex.Button ButtonFinish
            {
                get
                {
                    return _buttonfinishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonFinish item info.
            /// </summary>
            [RepositoryItemInfo("5656e623-e1d6-41f0-804d-2c7609d79c6d")]
            public virtual RepoItemInfo ButtonFinishInfo
            {
                get
                {
                    return _buttonfinishInfo;
                }
            }

            /// <summary>
            /// The MenuAutomationIdsFittingAction item.
            /// </summary>
            [RepositoryItem("5ecb5f89-0a58-4f91-bbd9-6dd9c3e2e2c6")]
            public virtual Ranorex.MenuItem MenuAutomationIdsFittingAction
            {
                get
                {
                    return _menuautomationidsfittingactionInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuAutomationIdsFittingAction item info.
            /// </summary>
            [RepositoryItemInfo("5ecb5f89-0a58-4f91-bbd9-6dd9c3e2e2c6")]
            public virtual RepoItemInfo MenuAutomationIdsFittingActionInfo
            {
                get
                {
                    return _menuautomationidsfittingactionInfo;
                }
            }

            /// <summary>
            /// The MenuAutomationIdsHelpAction item.
            /// </summary>
            [RepositoryItem("afc185ef-fed1-4f6e-83c7-290429ae75f7")]
            public virtual Ranorex.MenuItem MenuAutomationIdsHelpAction
            {
                get
                {
                    return _menuautomationidshelpactionInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuAutomationIdsHelpAction item info.
            /// </summary>
            [RepositoryItemInfo("afc185ef-fed1-4f6e-83c7-290429ae75f7")]
            public virtual RepoItemInfo MenuAutomationIdsHelpActionInfo
            {
                get
                {
                    return _menuautomationidshelpactionInfo;
                }
            }

            /// <summary>
            /// The MenuAutomationIdsHelpAction1 item.
            /// </summary>
            [RepositoryItem("9f9d1ad9-228d-4bac-ba9b-e2961856a12c")]
            public virtual Ranorex.MenuItem MenuAutomationIdsHelpAction1
            {
                get
                {
                    return _menuautomationidshelpaction1Info.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuAutomationIdsHelpAction1 item info.
            /// </summary>
            [RepositoryItemInfo("9f9d1ad9-228d-4bac-ba9b-e2961856a12c")]
            public virtual RepoItemInfo MenuAutomationIdsHelpAction1Info
            {
                get
                {
                    return _menuautomationidshelpaction1Info;
                }
            }

            /// <summary>
            /// The MenuAutomationIdsEditAction item.
            /// </summary>
            [RepositoryItem("de7bcafb-68a4-4b4d-b31e-3b841cc41f36")]
            public virtual Ranorex.MenuItem MenuAutomationIdsEditAction
            {
                get
                {
                    return _menuautomationidseditactionInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuAutomationIdsEditAction item info.
            /// </summary>
            [RepositoryItemInfo("de7bcafb-68a4-4b4d-b31e-3b841cc41f36")]
            public virtual RepoItemInfo MenuAutomationIdsEditActionInfo
            {
                get
                {
                    return _menuautomationidseditactionInfo;
                }
            }

            /// <summary>
            /// The NavigationAutomationIdsMainAutomationId item.
            /// </summary>
            [RepositoryItem("5c86eeca-14b8-42b8-a248-d36a22199902")]
            public virtual Ranorex.RadioButton NavigationAutomationIdsMainAutomationId
            {
                get
                {
                    return _navigationautomationidsmainautomationidInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The NavigationAutomationIdsMainAutomationId item info.
            /// </summary>
            [RepositoryItemInfo("5c86eeca-14b8-42b8-a248-d36a22199902")]
            public virtual RepoItemInfo NavigationAutomationIdsMainAutomationIdInfo
            {
                get
                {
                    return _navigationautomationidsmainautomationidInfo;
                }
            }

            /// <summary>
            /// The NavigationAutomationIdsMainAutomationId1 item.
            /// </summary>
            [RepositoryItem("ce36667b-1420-452c-966c-d012302c444c")]
            public virtual Ranorex.RadioButton NavigationAutomationIdsMainAutomationId1
            {
                get
                {
                    return _navigationautomationidsmainautomationid1Info.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The NavigationAutomationIdsMainAutomationId1 item info.
            /// </summary>
            [RepositoryItemInfo("ce36667b-1420-452c-966c-d012302c444c")]
            public virtual RepoItemInfo NavigationAutomationIdsMainAutomationId1Info
            {
                get
                {
                    return _navigationautomationidsmainautomationid1Info;
                }
            }

            /// <summary>
            /// The Text65535 item.
            /// </summary>
            [RepositoryItem("dce81d72-c118-4262-8957-afa498314810")]
            public virtual Ranorex.Text Text65535
            {
                get
                {
                    return _text65535Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text65535 item info.
            /// </summary>
            [RepositoryItemInfo("dce81d72-c118-4262-8957-afa498314810")]
            public virtual RepoItemInfo Text65535Info
            {
                get
                {
                    return _text65535Info;
                }
            }

            /// <summary>
            /// The ButtonOK1 item.
            /// </summary>
            [RepositoryItem("56600c0f-cc40-4148-91ca-157bbb71057e")]
            public virtual Ranorex.Button ButtonOK1
            {
                get
                {
                    return _buttonok1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK1 item info.
            /// </summary>
            [RepositoryItemInfo("56600c0f-cc40-4148-91ca-157bbb71057e")]
            public virtual RepoItemInfo ButtonOK1Info
            {
                get
                {
                    return _buttonok1Info;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("deaf3d12-ae16-4220-8313-5b9d3f6f3c90")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("deaf3d12-ae16-4220-8313-5b9d3f6f3c90")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }

            /// <summary>
            /// The ListBox item.
            /// </summary>
            [RepositoryItem("fbcb05d9-3b45-4752-8040-0baa68128a3c")]
            public virtual Ranorex.List ListBox
            {
                get
                {
                    return _listboxInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The ListBox item info.
            /// </summary>
            [RepositoryItemInfo("fbcb05d9-3b45-4752-8040-0baa68128a3c")]
            public virtual RepoItemInfo ListBoxInfo
            {
                get
                {
                    return _listboxInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("ba1cf351-1a8d-4f26-bda5-f1a1df6903e4")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _australiaInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, false, "ba1cf351-1a8d-4f26-bda5-f1a1df6903e4", "")
            {
                _australiaInfo = new RepoItemInfo(this, "Australia", "listitem[@text=$TxtMkt]", 30000, null, "b7a02ea0-8d2b-48df-8724-4938dd117fa4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ba1cf351-1a8d-4f26-bda5-f1a1df6903e4")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ba1cf351-1a8d-4f26-bda5-f1a1df6903e4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Australia item.
            /// </summary>
            [RepositoryItem("b7a02ea0-8d2b-48df-8724-4938dd117fa4")]
            public virtual Ranorex.ListItem Australia
            {
                get
                {
                    return _australiaInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Australia item info.
            /// </summary>
            [RepositoryItemInfo("b7a02ea0-8d2b-48df-8724-4938dd117fa4")]
            public virtual RepoItemInfo AustraliaInfo
            {
                get
                {
                    return _australiaInfo;
                }
            }
        }

        /// <summary>
        /// The MyReSoundAppFolder folder.
        /// </summary>
        [RepositoryFolder("eb4ad3f2-ce76-4e5e-ab3b-9571cc6fe117")]
        public partial class MyReSoundAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new MyReSound  folder.
            /// </summary>
            public MyReSoundAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyReSound", "/dom[@domain='online.gnresound.com.au']", parentFolder, 30000, null, false, "eb4ad3f2-ce76-4e5e-ab3b-9571cc6fe117", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eb4ad3f2-ce76-4e5e-ab3b-9571cc6fe117")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eb4ad3f2-ce76-4e5e-ab3b-9571cc6fe117")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The SmartFit1AppFolder folder.
        /// </summary>
        [RepositoryFolder("de40901e-2d4c-4fa3-97c8-dc4331311fd3")]
        public partial class SmartFit1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _partobjectnametextblockInfo;

            /// <summary>
            /// Creates a new SmartFit1  folder.
            /// </summary>
            public SmartFit1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("SmartFit1", "/contextmenu[@processname='SmartFit' and @win32ownerwindowlevel='2']", parentFolder, 30000, null, false, "de40901e-2d4c-4fa3-97c8-dc4331311fd3", "")
            {
                _partobjectnametextblockInfo = new RepoItemInfo(this, "PARTObjectNameTextBlock", "?/?/text[@automationid='PART_ObjectNameTextBlock']", 30000, null, "853f59bf-6472-4825-877f-43d08617f3df");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("de40901e-2d4c-4fa3-97c8-dc4331311fd3")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("de40901e-2d4c-4fa3-97c8-dc4331311fd3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PARTObjectNameTextBlock item.
            /// </summary>
            [RepositoryItem("853f59bf-6472-4825-877f-43d08617f3df")]
            public virtual Ranorex.Text PARTObjectNameTextBlock
            {
                get
                {
                    return _partobjectnametextblockInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PARTObjectNameTextBlock item info.
            /// </summary>
            [RepositoryItemInfo("853f59bf-6472-4825-877f-43d08617f3df")]
            public virtual RepoItemInfo PARTObjectNameTextBlockInfo
            {
                get
                {
                    return _partobjectnametextblockInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
