///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Market_Preferences
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PreferenceWindow recording.
    /// </summary>
    [TestModule("8d0374c5-698e-42d7-9a4b-5a687d8e760f", ModuleType.Recording, 1)]
    public partial class PreferenceWindow : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Market_PreferencesRepository repository.
        /// </summary>
        public static Market_PreferencesRepository repo = Market_PreferencesRepository.Instance;

        static PreferenceWindow instance = new PreferenceWindow();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PreferenceWindow()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PreferenceWindow Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(0));
            Delay.Duration(4000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Window.Thumb' at Center.", repo.Window.ThumbInfo, new RecordItemIndex(1));
            //repo.Window.Thumb.MoveTo();
            //Delay.Milliseconds(200);
            
            Mouse_Click_Copy_of_Save_Button(repo.Window.Copy_of_Save_ButtonInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(3));
            Delay.Duration(4000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Window.Close' at Center.", repo.Window.CloseInfo, new RecordItemIndex(4));
            //repo.Window.Close.MoveTo();
            //Delay.Milliseconds(200);
            
            Mouse_Click_Close(repo.Window.CloseInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(6));
            Delay.Duration(4000, false);
            
            Mouse_Click_Exit_Without_saving(repo.Window.PARTPositiveButtonInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
