///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Market_Preferences
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TestDevice_Excelfile_Comparison recording.
    /// </summary>
    [TestModule("1b267de0-f7bf-499a-aee0-df894aff58ee", ModuleType.Recording, 1)]
    public partial class TestDevice_Excelfile_Comparison : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Market_PreferencesRepository repository.
        /// </summary>
        public static Market_PreferencesRepository repo = Market_PreferencesRepository.Instance;

        static TestDevice_Excelfile_Comparison instance = new TestDevice_Excelfile_Comparison();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TestDevice_Excelfile_Comparison()
        {
            txtMarketname = "";
            txtBuildname = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TestDevice_Excelfile_Comparison Instance
        {
            get { return instance; }
        }

#region Variables

        string _txtMarketname;

        /// <summary>
        /// Gets or sets the value of variable txtMarketname.
        /// </summary>
        [TestVariable("493fa994-6933-49f6-89d2-ec9aa4d5e225")]
        public string txtMarketname
        {
            get { return _txtMarketname; }
            set { _txtMarketname = value; }
        }

        string _txtBuildname;

        /// <summary>
        /// Gets or sets the value of variable txtBuildname.
        /// </summary>
        [TestVariable("ce285caa-cd9d-4cd4-8457-5372b29c6228")]
        public string txtBuildname
        {
            get { return _txtBuildname; }
            set { _txtBuildname = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Test_Device_UserCodeCollection.TestDevice_ExcelComparison(txtMarketname, txtBuildname);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
