///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Market_Preferences
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The User_Preferences_Record_Modules recording.
    /// </summary>
    [TestModule("ec400c63-49bb-4650-8a02-9cb53943edef", ModuleType.Recording, 1)]
    public partial class User_Preferences_Record_Modules : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Market_PreferencesRepository repository.
        /// </summary>
        public static Market_PreferencesRepository repo = Market_PreferencesRepository.Instance;

        static User_Preferences_Record_Modules instance = new User_Preferences_Record_Modules();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public User_Preferences_Record_Modules()
        {
            txtMarketname = "";
            txtBuildname = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static User_Preferences_Record_Modules Instance
        {
            get { return instance; }
        }

#region Variables

        string _txtMarketname;

        /// <summary>
        /// Gets or sets the value of variable txtMarketname.
        /// </summary>
        [TestVariable("c35e1332-b3cc-4e38-975f-17bac21e10d1")]
        public string txtMarketname
        {
            get { return _txtMarketname; }
            set { _txtMarketname = value; }
        }

        string _txtBuildname;

        /// <summary>
        /// Gets or sets the value of variable txtBuildname.
        /// </summary>
        [TestVariable("8ea99ec6-e25d-4184-aaef-0e521ec6b70a")]
        public string txtBuildname
        {
            get { return _txtBuildname; }
            set { _txtBuildname = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            User_Preferences_UserCode.Default_Language_Comparison(txtMarketname, txtBuildname);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(1));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Window.Edit' at Center.", repo.Window.EditInfo, new RecordItemIndex(2));
            repo.Window.Edit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SmartFit.Preferences' at Center.", repo.SmartFit.PreferencesInfo, new RecordItemIndex(3));
            repo.SmartFit.Preferences.Click();
            Delay.Milliseconds(200);
            
            User_Preferences_UserCode.Fetching_UserPreference(txtBuildname);
            Delay.Milliseconds(0);
            
            User_Preferences_UserCode.Fetching_UserPreference_DefaultValues(txtBuildname);
            Delay.Milliseconds(0);
            
            //User_Preferences_UserCode.To_Find_Market_Preference_is_present_in_excel_or_Not();
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
