///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Market_Preferences
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validating_URL recording.
    /// </summary>
    [TestModule("72e2223e-550b-4f3c-a678-d477b71616e3", ModuleType.Recording, 1)]
    public partial class Validating_URL : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Market_PreferencesRepository repository.
        /// </summary>
        public static Market_PreferencesRepository repo = Market_PreferencesRepository.Instance;

        static Validating_URL instance = new Validating_URL();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validating_URL()
        {
            URL_Marketname = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validating_URL Instance
        {
            get { return instance; }
        }

#region Variables

        string _URL_Marketname;

        /// <summary>
        /// Gets or sets the value of variable URL_Marketname.
        /// </summary>
        [TestVariable("027838b8-32ad-4c52-a1ed-eb147cf20fbd")]
        public string URL_Marketname
        {
            get { return _URL_Marketname; }
            set { _URL_Marketname = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Links_UserCodeCollection.Kill_All_Open_Browsers();
            Delay.Milliseconds(0);
            
            Links_UserCodeCollection.E_Commerces_Link2(URL_Marketname);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FSWModule_Repo.PARTHamburgerToggle' at Center.", repo.FSWModule_Repo.PARTHamburgerToggleInfo, new RecordItemIndex(2));
            repo.FSWModule_Repo.PARTHamburgerToggle.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(3));
            Delay.Duration(3000, false);
            
            Links_UserCodeCollection.Resound_WebSite2(URL_Marketname);
            Delay.Milliseconds(0);
            
            Links_UserCodeCollection.ReSound_eCademy2(URL_Marketname);
            Delay.Milliseconds(0);
            
            Links_UserCodeCollection.UserGuide_and_CableGuide2(URL_Marketname);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
